/* EdgeCore-1 Firmware — Auto-generated by edgecore1_runtime.py
 * Infinar Scientia | April 2026
 * Compile: riscv32-unknown-elf-gcc -march=rv32imc -O2 -o firmware.elf firmware.c
 * Link:    riscv32-unknown-elf-objcopy -O ihex firmware.elf firmware.hex
 */
#include <stdint.h>

/* CSR Memory Map */
#define CSR_MAC_CTRL   (*(volatile uint32_t*)0x40000000)
#define CSR_TILE_INDEX (*(volatile uint32_t*)0x40000004)
#define CSR_SPARSE_WR  (*(volatile uint32_t*)0x40000008)
#define CSR_SPARSE_REQ (*(volatile uint32_t*)0x4000000C)
#define CSR_SPARSE_RD  (*(volatile uint32_t*)0x40000010)
#define CSR_ACC_CTRL   (*(volatile uint32_t*)0x40000014)
#define CSR_STATUS     (*(volatile uint32_t*)0x40000020)
#define ACC_BASE       ((volatile int32_t*)0x80000000)

#define SPARSITY_THRESH 13
#define NUM_TILES       4000

static inline void write_mask_byte(uint32_t tile, uint32_t byte_idx, uint8_t val) {
    CSR_SPARSE_WR = (1u) | ((tile*8 + byte_idx) << 8) | ((uint32_t)val << 26);
    CSR_SPARSE_WR = 0; /* deassert wr_en */
}

static inline int tile_is_active(uint32_t tile_idx) {
    CSR_TILE_INDEX = tile_idx;
    CSR_SPARSE_REQ = 1;
    CSR_SPARSE_REQ = 0;
    while (!(CSR_SPARSE_RD & 0x2)); /* wait eval_done */
    return (CSR_SPARSE_RD & 0x1);  /* tile_active */
}

static inline void wait_layer_done(void) {
    while (!(CSR_STATUS & 0x1)); /* poll layer_done */
}

void edgecore1_inference(const int8_t *activations, const int8_t *weights,
                          uint8_t *result_class) {
    uint32_t t, b;

    /* 1. Clear accumulators */
    CSR_ACC_CTRL = 1; CSR_ACC_CTRL = 0;

    /* 2. Load sparsity masks (from weight tensor, pre-computed by TVM) */
    /* In production: masks DMA'd from LPDDR5 before this function */
    /* Here: placeholder — real masks written by DMA engine */

    /* 3. Enable MAC clock */
    CSR_MAC_CTRL = 0x4; /* clk_en=1 */

    /* 4. Dispatch tiles */
    for (t = 0; t < NUM_TILES; t++) {
        if (tile_is_active(t)) {
            /* Write tile_a and tile_w via DMA (simplified: direct write) */
            /* In production: DMA transfers 512 bits from SRAM to MAC input regs */
            CSR_MAC_CTRL = 0x5; /* start=1, clk_en=1 */
            CSR_MAC_CTRL = 0x4; /* deassert start */
        }
    }

    /* 5. Wait for completion */
    wait_layer_done();

    /* 6. Gate MAC clock to save power */
    CSR_MAC_CTRL = 0x0;

    /* 7. Argmax over 256 accumulators */
    int32_t max_val = ACC_BASE[0];
    uint8_t max_idx = 0;
    for (uint32_t i = 1; i < 256; i++) {
        if (ACC_BASE[i] > max_val) {
            max_val = ACC_BASE[i];
            max_idx = (uint8_t)i;
        }
    }
    *result_class = max_idx;
}

int main(void) {
    /* Placeholder: in production, activations loaded from LPDDR5 */
    static int8_t activations[512] = {0};
    static int8_t weights[512]     = {0};
    uint8_t result = 0;
    while (1) {
        edgecore1_inference(activations, weights, &result);
        /* Result written to output register — host reads via SPI */
    }
    return 0;
}
